const API=(window.LOAN_API_URL||'http://localhost:8000').replace(/\/$/,'');
const form=document.getElementById('score-form'),error=document.getElementById('form-error');
const status=document.getElementById('api-status'),light=document.getElementById('api-light');
async function checkHealth(){try{const r=await fetch(`${API}/health`);if(!r.ok)throw Error();status.textContent='Model API connected';light.classList.add('online')}catch{status.textContent='Model API is waking up or unavailable';light.classList.remove('online')}}
checkHealth();
form.addEventListener('submit',async event=>{event.preventDefault();error.hidden=true;if(!form.reportValidity())return;const button=form.querySelector('.submit');button.disabled=true;button.firstChild.textContent='Running scenario… ';
 const data=Object.fromEntries(new FormData(form).entries());data.credit_policy_met=data.credit_policy_met==='true';for(const [key,value] of Object.entries(data))if(key!=='purpose'&&key!=='credit_policy_met')data[key]=Number(value);
 try{const response=await fetch(`${API}/api/score`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok){const first=Array.isArray(result.detail)?result.detail[0]?.msg:result.detail;throw Error(first||'The model could not score this scenario.')}const pct=Math.max(0,Math.min(100,result.not_fully_paid_score*100));document.getElementById('result-value').textContent=`${pct.toFixed(1)}%`;document.getElementById('score-fill').style.width=`${pct}%`;document.getElementById('input-count').textContent=`${result.inputs_used} of 19`;document.getElementById('result-empty').hidden=true;document.getElementById('result-ready').hidden=false;status.textContent='Model API connected';light.classList.add('online');document.querySelector('.result-card').scrollIntoView({behavior:'smooth',block:'nearest'});
 }catch(e){error.textContent=e.message+' If the free service is waking, wait a moment and try again.';error.hidden=false;status.textContent='Model API unavailable';light.classList.remove('online')}finally{button.disabled=false;button.firstChild.textContent='Run model scenario '}});
form.addEventListener('reset',()=>{error.hidden=true;document.getElementById('result-ready').hidden=true;document.getElementById('result-empty').hidden=false});
